name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Nitro build
        run: pnpm run build

      - name: Install pkg
        run: npm install -g pkg

      - name: Package for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          pkg .output/server/index.mjs --targets node18-linux-x64 --output build/output-linux

      - name: Package for macOS
        if: matrix.os == 'macos-latest'
        run: |
          pkg .output/server/index.mjs --targets node18-macos-x64 --output build/output-macos

      - name: Package for Windows
        if: matrix.os == 'windows-latest'
        run: |
          pkg .output/server/index.mjs --targets node18-win-x64 --output build/output-windows

      - name: Upload artifacts for Linux
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: build-linux
          path: build/output-linux

      - name: Upload artifacts for macOS
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: build-macos
          path: build/output-macos

      - name: Upload artifacts for Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: build-windows
          path: build/output-windows
