name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Nitro build
        run: pnpm run build
      
      - name: Install bun
        run: npm install -g bun

      - name: Package for Linux (x64)
        run: |
          bun build ./.output/server/index.mjs --target=bun-linux-x64 --compile --outfile ./build/output-linux-x64
      
      - name: Package for Linux (arm64)
        run: |
          bun build ./.output/server/index.mjs --target=bun-linux-arm64 --compile --outfile ./build/output-linux-arm64

      - name: Package for macOS (arm64)
        run: |
          bun build ./.output/server/index.mjs --target=bun-darwin-arm64 --compile --outfile ./build/output-macos-arm64

      - name: Package for macOS (Intel)
        run: |
          bun build ./.output/server/index.mjs --target=bun-darwin-x64 --compile --outfile ./build/output-macos-x64

      - name: Package for Windows
        run: |
          bun build ./.output/server/index.mjs --target=bun-windows-x64 --compile --outfile ./build/output-windows

      - name: Upload artifacts for Linux (x64)
        uses: actions/upload-artifact@v3
        with:
          name: build-linux-x64
          path: ./build/output-linux-x64

      - name: Upload artifacts for Linux (arm64)
        uses: actions/upload-artifact@v3
        with:
          name: build-linux-x64
          path: ./build/output-linux-arm64

      - name: Upload artifacts for macOS (arm64)
        uses: actions/upload-artifact@v3
        with:
          name: build-macos-arm64
          path: build/output-macos-arm64

      - name: Upload artifacts for macOS (x64)
        uses: actions/upload-artifact@v3
        with:
          name: build-macos-x64
          path: build/output-macos-x64

      - name: Upload artifacts for Windows
        uses: actions/upload-artifact@v3
        with:
          name: build-windows
          path: build/output-windows
