name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Nitro build
        run: pnpm run build

      - name: Install pkg
        run: npm install -g pkg

      - name: Package server with pkg
        run: |
          pkg .output/server/index.mjs --targets node18-${{ matrix.os }}-x64 --output build/output-${{ matrix.os }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: build/output-${{ matrix.os }}
