name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        node-version: [18.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Nitro build
        run: pnpm run build

      - name: Install nexe
        run: npm install -g nexe

      - name: Clone node (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          cp $(which node) ./node
      
      - name: Package for macOS
        if: matrix.os == 'macos-latest'
        run: |
          npx nexe -i ./.output/server/index.mjs --asset ./node -output ./build/macos

      - name: Upload artifacts for macOS
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: build-macos-x64
          path: ./build/macos
