name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-package:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.x]
        architecture: [x64, arm64]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Nitro build
        run: pnpm run build

      - name: Build as CommonJS
        run: npx esbuild ./.output/server/index.mjs --bundle --platform=node --outfile=./.output/server/index.cjs --external:sleep

      - name: Package with pkg
        run: npx pkg ./.output/server/index.cjs --targets node18-macos-${{ matrix.architecture }} --output ./stremify-macos-${{ matrix.architecture }}

      - name: Code sign binary
        run: codesign --sign - --force --deep ./stremify-macos-${{ matrix.architecture }}

      - name: Upload artifact for macOS
        uses: actions/upload-artifact@v4
        with:
          name: build-macos-${{ matrix.architecture }}
          path: ./stremify-macos-${{ matrix.architecture }}
