name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-package:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Nitro build
        run: bun run build

      - name: Compile to single executable
        run: bun build .output/server/index.mjs --compile --outfile ./build/macos

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-macos-x64
          path: ./build/macos
